# Removed the obsolete 'version' attribute
services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      # Remova as configurações de email não utilizadas
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - default

  db:
    image: postgres:14
    container_name: zeus_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 147afj
      POSTGRES_DB: zeus_admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default

  api:
    build: .
    container_name: zeus_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 147afj
      DB_NAME: zeus_admin
      BODY_PARSER_LIMIT: 50mb
      PORT: 3000
      JWT_SECRET: your_jwt_secret_key
      NODE_ENV: production
      DB_SYNC: "false" # Desativar sincronização automática em produção
    ports:
      - "3000:3000"  # Mapeamento direto da porta
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    working_dir: /app
    command: sh -c "while ! pg_isready -h db -U postgres; do sleep 1; done && node dist/index.js"
    networks:
      - default

networks:
  default:
    name: projeto-zeus_default
    driver: bridge

volumes:
  pgdata:
  postgres_data: